[package]
name = "rust"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12.5", features = ["json"] }
tokio = { version = "1", features = ["full"] }
# serde for json serialization and deserialization 
serde = { version = "1.0", features = ["derive"] }
